import logging
import uuid
from datetime import datetime, timezone
from html import escape

import httpx

from infra_brain.callbacks.write_gate import gate_external_write
from infra_brain.config import get_settings
from infra_brain.db.models import ConfluencePage
from infra_brain.db.session import get_session

logger = logging.getLogger(__name__)


def build_domain_page_body(domain: str, resources: list[dict]) -> str:
    rows = "".join(
        f"<tr><td>{escape(str(r.get('name', '')))}</td>"
        f"<td>{escape(str(r.get('type', '')))}</td>"
        f"<td>{escape(str(r.get('last_seen', '')))}</td></tr>"
        for r in resources
    )
    return (
        f"<h2>{escape(domain.upper())} Infrastructure</h2>"
        f"<p>Auto-generated by Infra Brain. Last updated: {datetime.now(timezone.utc).isoformat()}</p>"
        f"<table><tr><th>Name</th><th>Type</th><th>Last Seen</th></tr>{rows}</table>"
    )


def _get_auth():
    s = get_settings()
    return (s.confluence_user_email, s.confluence_token)


def _find_existing_page(title: str, space_key: str) -> str | None:
    s = get_settings()
    resp = httpx.get(
        f"{s.confluence_url}/rest/api/content",
        params={"title": title, "spaceKey": space_key, "expand": "version"},
        auth=_get_auth(),
        timeout=s.api_timeout_seconds,
    )
    resp.raise_for_status()
    results = resp.json().get("results", [])
    return results[0]["id"] if results else None


def upsert_confluence_page(domain: str, title: str, body: str) -> str:
    # F-004.3: pre-write DLP + audit gate — refuses BEFORE any HTTP call.
    gate_external_write(
        system="confluence",
        operation="upsert_confluence_page",
        payload=f"{title}\n{body}",
        agent_name="confluence",
    )
    s = get_settings()

    with get_session() as session:
        existing_page = session.query(ConfluencePage).filter_by(domain=domain).first()

    page_id = (
        existing_page.page_id
        if existing_page
        else _find_existing_page(title, s.confluence_space_key)
    )

    if page_id:
        # Update existing page
        resp = httpx.get(
            f"{s.confluence_url}/rest/api/content/{page_id}?expand=version",
            auth=_get_auth(),
            timeout=s.api_timeout_seconds,
        )
        resp.raise_for_status()
        current_version = resp.json()["version"]["number"]

        resp = httpx.put(
            f"{s.confluence_url}/rest/api/content/{page_id}",
            json={
                "version": {"number": current_version + 1},
                "title": title,
                "type": "page",
                "body": {"storage": {"value": body, "representation": "storage"}},
            },
            auth=_get_auth(),
            timeout=s.api_timeout_seconds,
        )
        resp.raise_for_status()
    else:
        # Create new page
        resp = httpx.post(
            f"{s.confluence_url}/rest/api/content",
            json={
                "type": "page",
                "title": title,
                "space": {"key": s.confluence_space_key},
                "body": {"storage": {"value": body, "representation": "storage"}},
            },
            auth=_get_auth(),
            timeout=s.api_timeout_seconds,
        )
        resp.raise_for_status()
        page_id = resp.json()["id"]

    with get_session() as session:
        existing = session.query(ConfluencePage).filter_by(domain=domain).first()
        if existing:
            existing.page_id = page_id
            existing.last_updated = datetime.now(timezone.utc)
        else:
            session.add(
                ConfluencePage(
                    id=uuid.uuid4(),
                    domain=domain,
                    page_id=page_id,
                    last_updated=datetime.now(timezone.utc),
                )
            )
        session.commit()

    return page_id
