"""Module tests for infra_brain.digest (MR-E TEST-4).

build_digest_markdown() had zero direct test coverage — only touched
transitively (test_scripts_store.py, test_mcp_server.py, test_vendored_assets.py
reference "digest" for unrelated reasons). Uses a real in-memory SQLite
session (not a mock) so the actual COUNT/filter semantics are proven, not
just that certain methods were called.
"""

from contextlib import contextmanager
from datetime import datetime, timedelta, timezone
from unittest.mock import patch

import pytest
from sqlalchemy.orm import Session

from infra_brain.db.models import (
    ComplianceViolation,
    DriftEvent,
    EolRegistry,
    Resource,
    VulnQueueItem,
)
from infra_brain.digest import build_digest_markdown

from tests.support.pg import make_engine


@pytest.fixture
def engine():
    eng = make_engine()
    return eng


@pytest.fixture
def digest_session(engine):
    @contextmanager
    def _get_session():
        with Session(engine) as s:
            yield s

    with patch("infra_brain.digest.get_session", _get_session):
        yield engine


def _mk_resource(session, name="host-01"):
    r = Resource(
        domain="test",
        type="host",
        name=name,
        source="test",
        zone="corpor",
        last_seen=datetime.now(timezone.utc),
    )
    session.add(r)
    session.flush()
    return r.id


# ---------------------------------------------------------------------------
# Empty-fleet baseline
# ---------------------------------------------------------------------------


def test_build_digest_markdown_empty_db_reports_all_zeros(digest_session):
    md = build_digest_markdown()
    assert "| Open drift events | 0 |" in md
    assert "Open vulnerabilities | 0 (critical: 0)" in md
    assert "| EOL assets overdue | 0 |" in md
    assert "| Open compliance violations | 0 |" in md


def test_build_digest_markdown_includes_date_header(digest_session):
    now = datetime(2026, 7, 7, tzinfo=timezone.utc)
    md = build_digest_markdown(now=now)
    assert "2026-07-07" in md


def test_build_digest_markdown_ends_with_auto_generated_footer(digest_session):
    md = build_digest_markdown()
    assert md.strip().endswith("_Auto-generated by Infra Brain._")


# ---------------------------------------------------------------------------
# Open drift events
# ---------------------------------------------------------------------------


def test_build_digest_markdown_counts_only_open_drift(digest_session):
    with Session(digest_session) as s:
        rid = _mk_resource(s)
        s.add(DriftEvent(resource_id=rid, drift_type="config_drift", field="x", status="open"))
        s.add(DriftEvent(resource_id=rid, drift_type="config_drift", field="y", status="resolved"))
        s.commit()

    md = build_digest_markdown()
    assert "| Open drift events | 1 |" in md


# ---------------------------------------------------------------------------
# Vulnerabilities
# ---------------------------------------------------------------------------


def test_build_digest_markdown_counts_open_and_triage_as_open_vulns(digest_session):
    with Session(digest_session) as s:
        rid = _mk_resource(s)
        s.add(
            VulnQueueItem(resource_id=rid, cve_id="CVE-2021-0001", severity="high", status="open")
        )
        s.add(
            VulnQueueItem(resource_id=rid, cve_id="CVE-2021-0002", severity="low", status="triage")
        )
        s.add(
            VulnQueueItem(
                resource_id=rid, cve_id="CVE-2021-0003", severity="high", status="resolved"
            )
        )
        s.commit()

    md = build_digest_markdown()
    assert "Open vulnerabilities | 2 " in md


def test_build_digest_markdown_counts_critical_subset_of_open_vulns(digest_session):
    with Session(digest_session) as s:
        rid = _mk_resource(s)
        s.add(
            VulnQueueItem(
                resource_id=rid, cve_id="CVE-2021-1001", severity="critical", status="open"
            )
        )
        s.add(
            VulnQueueItem(resource_id=rid, cve_id="CVE-2021-1002", severity="high", status="open")
        )
        # Resolved critical must not count even though severity matches.
        s.add(
            VulnQueueItem(
                resource_id=rid, cve_id="CVE-2021-1003", severity="critical", status="resolved"
            )
        )
        s.commit()

    md = build_digest_markdown()
    assert "critical: 1" in md


# ---------------------------------------------------------------------------
# EOL overdue
# ---------------------------------------------------------------------------


def test_build_digest_markdown_counts_only_overdue_eol_assets(digest_session):
    now = datetime(2026, 7, 7, tzinfo=timezone.utc)
    with Session(digest_session) as s:
        rid = _mk_resource(s)
        s.add(
            EolRegistry(resource_id=rid, asset_name="past-eol", eol_date=now - timedelta(days=30))
        )
        s.add(
            EolRegistry(resource_id=rid, asset_name="future-eol", eol_date=now + timedelta(days=30))
        )
        s.add(EolRegistry(resource_id=rid, asset_name="no-eol-date", eol_date=None))
        s.commit()

    md = build_digest_markdown(now=now)
    assert "| EOL assets overdue | 1 |" in md


def test_build_digest_markdown_handles_naive_eol_dates(digest_session):
    """EolRegistry rows written before tz-awareness was enforced everywhere
    could carry a naive datetime — must not raise a tz-comparison TypeError."""
    now = datetime(2026, 7, 7, tzinfo=timezone.utc)
    with Session(digest_session) as s:
        rid = _mk_resource(s)
        s.add(
            EolRegistry(
                resource_id=rid,
                asset_name="naive-past-eol",
                eol_date=datetime(2020, 1, 1),  # naive, no tzinfo
            )
        )
        s.commit()

    md = build_digest_markdown(now=now)
    assert "| EOL assets overdue | 1 |" in md


# ---------------------------------------------------------------------------
# Compliance violations
# ---------------------------------------------------------------------------


def test_build_digest_markdown_counts_only_open_compliance_violations(digest_session):
    with Session(digest_session) as s:
        s.add(ComplianceViolation(rule="r1", host="h1", status="open"))
        s.add(ComplianceViolation(rule="r2", host="h2", status="resolved"))
        s.commit()

    md = build_digest_markdown()
    assert "| Open compliance violations | 1 |" in md


# ---------------------------------------------------------------------------
# post_digest — best-effort Confluence publish
# ---------------------------------------------------------------------------


def test_post_digest_returns_markdown_even_when_publish_fails(digest_session):
    from infra_brain import digest as digest_mod

    with (
        patch.object(digest_mod, "logger") as mock_logger,
        patch(
            "infra_brain.tools.confluence.upsert_confluence_page",
            side_effect=RuntimeError("confluence down"),
        ),
    ):
        md = digest_mod.post_digest()

    assert "Infra Brain — Fleet Digest" in md
    mock_logger.warning.assert_called()


def test_post_digest_logs_but_does_not_raise_on_write_gate_denial(digest_session):
    from infra_brain import digest as digest_mod

    with (
        patch.object(digest_mod, "logger") as mock_logger,
        patch(
            "infra_brain.tools.confluence.upsert_confluence_page",
            side_effect=PermissionError("blocked by write gate"),
        ),
    ):
        md = digest_mod.post_digest()

    assert "Infra Brain — Fleet Digest" in md
    mock_logger.warning.assert_called()
    assert "BLOCKED" in mock_logger.warning.call_args[0][0]
