"""Route-parity guard (Phase 3 Task 12).

Builds the full app via create_app() and asserts that the complete set of
(method, path) tuples matches the frozen expected set below.  Any future
change that adds, drops, or renames a route will fail this test.

A second assertion verifies that no (method, path) pair is mounted twice
(no duplicate route registrations).

How routes are collected:
    FastAPI stores included routers as _IncludedRouter wrapper objects (not
    directly as APIRoute entries) on app.router.routes.  _collect_routes()
    uses isinstance() against the public fastapi.routing.APIRoute class to
    identify real route entries, and recurses into wrapper objects by:
      1. Trying r.include_context.included_router (the documented internal path)
      2. Falling back to r.original_router (alias to the same object in current
         FastAPI versions, kept as belt-and-suspenders)
      3. Falling back to r.routes for any other container-like object (e.g. Mount)
    A cycle guard (set of id()s) prevents infinite recursion.  The result is
    all 76 (method, path) pairs the running app serves.
"""

from __future__ import annotations

from collections import Counter

from fastapi.routing import APIRoute

from infra_brain.main import create_app

# ---------------------------------------------------------------------------
# Route collector
# ---------------------------------------------------------------------------


def _collect_routes(router, _seen: set[int] | None = None) -> list[tuple[str, str]]:
    """Recursively collect (METHOD, path) from a router or route-container object.

    Uses isinstance(r, APIRoute) — the public FastAPI class — rather than
    string-matching type names, so the check is version-stable.  Recurses into
    _IncludedRouter wrappers via include_context.included_router (preferred)
    with original_router as a fallback, then .routes for any other container.
    A cycle guard prevents re-visiting the same router object.
    """
    if _seen is None:
        _seen = set()

    router_id = id(router)
    if router_id in _seen:
        return []
    _seen.add(router_id)

    result: list[tuple[str, str]] = []
    for r in router.routes:
        if isinstance(r, APIRoute):
            for method in sorted(r.methods):
                result.append((method, r.path))
        else:
            # Prefer the proven include_context path (FastAPI internal structure).
            ic = getattr(r, "include_context", None)
            if ic is not None:
                sub_router = getattr(ic, "included_router", None)
                if sub_router is not None and id(sub_router) not in _seen:
                    result.extend(_collect_routes(sub_router, _seen))
                    continue

            # Belt-and-suspenders: try original_router (same object in current
            # FastAPI versions; kept in case include_context shape shifts).
            orig = getattr(r, "original_router", None)
            if orig is not None and id(orig) not in _seen:
                result.extend(_collect_routes(orig, _seen))
                continue

            # Last resort: walk any .routes container directly (e.g. Mount).
            sub_routes = getattr(r, "routes", None)
            if sub_routes is not None:
                for sr in sub_routes:
                    if isinstance(sr, APIRoute):
                        for method in sorted(sr.methods):
                            result.append((method, sr.path))

    return result


# ---------------------------------------------------------------------------
# Frozen expected route set
# (generated by introspecting the app at Task-12 commit; sorted for readability)
# ---------------------------------------------------------------------------

EXPECTED_ROUTES: set[tuple[str, str]] = {
    # ── Root redirect ────────────────────────────────────────────────────────
    ("GET", "/"),
    # ── Webhooks + health (webhooks.py) ──────────────────────────────────────
    ("GET", "/health"),
    ("GET", "/healthz"),
    ("GET", "/metrics"),  # Prometheus scrape endpoint, same trust tier (TRK-093)
    ("GET", "/api/ops/heartbeat"),
    ("GET", "/scan_points"),
    ("POST", "/actions/{action_id}/approve"),
    ("POST", "/actions/{action_id}/reject"),
    ("POST", "/integrations/{proposal_id}/approve"),
    ("POST", "/sweeps/{domain}"),
    ("POST", "/webhooks/ansible"),
    ("POST", "/webhooks/cloud/{provider}"),
    ("POST", "/webhooks/generic"),
    ("POST", "/webhooks/gitlab"),
    ("POST", "/webhooks/incident/ack"),  # TRK-242 (GitLab #113)
    ("POST", "/webhooks/ops-alert"),  # TRK-135/TRK-329 in-app alert receiver
    ("POST", "/webhooks/octopus"),
    # ── Chatops bot (chatops.py, GitLab #111) — HMAC-gated, not session ─────
    ("POST", "/webhooks/chatops/slack/events"),
    ("POST", "/webhooks/chatops/slack/command"),
    ("POST", "/webhooks/chatops/teams"),
    # ── Auth (dashboard_auth.py) ─────────────────────────────────────────────
    ("GET", "/api/dashboard/me"),
    ("POST", "/api/dashboard/login"),
    ("POST", "/api/dashboard/logout"),
    # ── Fleet / health / version (api/routers/fleet.py) ──────────────────────
    ("GET", "/api/dashboard/collection_runs"),
    ("GET", "/api/dashboard/counts"),
    ("GET", "/api/dashboard/fleet"),
    ("GET", "/api/dashboard/fleet/{asset_id}/detail"),
    ("GET", "/api/dashboard/scan_points"),
    ("GET", "/api/dashboard/sites"),
    # Per-domain source inventory + UI visibility verdict (routers/sources.py).
    # The dashboard nav is built from this, so losing it silently degrades the
    # sidebar to "show everything" rather than erroring — worth a parity row.
    ("GET", "/api/dashboard/sources"),
    ("GET", "/api/dashboard/software"),
    ("GET", "/api/dashboard/software/vendors"),
    ("GET", "/api/dashboard/sweeps"),
    ("GET", "/api/dashboard/sweeps/{sweep_id}"),
    ("GET", "/api/dashboard/selfcheck"),
    ("GET", "/api/dashboard/system_health"),
    ("GET", "/api/dashboard/tags"),
    ("GET", "/api/dashboard/version"),
    ("POST", "/api/dashboard/sweeps/{domain}"),
    # ── Resources + EoL (api/routers/hosts.py — resources_router) ────────────
    ("GET", "/api/dashboard/eol"),
    ("GET", "/api/dashboard/resources"),
    ("GET", "/api/dashboard/resources/{resource_id}/linux"),
    ("GET", "/api/dashboard/resources/{resource_id}/ownership"),
    ("PUT", "/api/dashboard/resources/{resource_id}/ownership"),
    ("GET", "/api/dashboard/resources/{resource_id}/posture"),
    ("GET", "/api/dashboard/resources/{resource_id}/snapshots"),
    ("GET", "/api/dashboard/resources/{resource_id}/windows"),
    ("GET", "/api/dashboard/host-purpose-map"),
    ("PATCH", "/api/dashboard/eol/{eol_id}/migration"),
    ("POST", "/api/dashboard/resources"),
    ("POST", "/api/dashboard/resources/bulk"),
    # ── Network discovery / shadow-IT (api/routers/netdiscovery.py) ──────────
    ("GET", "/api/dashboard/netdiscovery/hosts"),
    # ── Host identity (api/routers/hosts.py — hosts_router) ──────────────────
    ("GET", "/api/dashboard/hosts"),
    ("GET", "/api/dashboard/hosts/{hostname}"),
    ("GET", "/api/dashboard/hosts/{hostname}/vulns"),
    ("GET", "/api/dashboard/hosts/{hostname}/purpose"),
    ("PUT", "/api/dashboard/hosts/{hostname}/purpose"),
    # ── MCP scoped-key management (api/routers/mcp_keys.py) ────────────────────
    ("GET", "/api/dashboard/mcp-keys"),
    ("GET", "/api/dashboard/mcp-keys/tools"),
    ("POST", "/api/dashboard/mcp-keys"),
    ("PATCH", "/api/dashboard/mcp-keys/{key_id}"),
    ("POST", "/api/dashboard/mcp-keys/{key_id}/revoke"),
    # ── RuntimeConfig tuning overrides (api/routers/runtime_config.py, TRK-303) ──
    ("GET", "/api/dashboard/runtime-config"),
    ("PUT", "/api/dashboard/runtime-config/{key}"),
    ("DELETE", "/api/dashboard/runtime-config/{key}"),
    # ── Derived settings catalog (api/routers/settings_catalog.py) ──
    ("GET", "/api/dashboard/settings-catalog"),
    ("PUT", "/api/dashboard/settings-catalog/{key}"),
    ("DELETE", "/api/dashboard/settings-catalog/{key}"),
    # ── Webhook subscription management (api/routers/webhook_subscriptions.py, #112) ──
    ("GET", "/api/dashboard/webhook-subscriptions"),
    ("POST", "/api/dashboard/webhook-subscriptions"),
    ("PATCH", "/api/dashboard/webhook-subscriptions/{sub_id}"),
    ("DELETE", "/api/dashboard/webhook-subscriptions/{sub_id}"),
    ("POST", "/api/dashboard/webhook-subscriptions/{sub_id}/test"),
    ("GET", "/api/dashboard/webhook-subscriptions/{sub_id}/deliveries"),
    # ── Read-only GraphQL query layer (api/graphql/router.py, GitLab #114) ──
    ("GET", "/api/graphql"),
    ("POST", "/api/graphql"),
    # ── Vuln queue + remediation (api/routers/vuln.py) ───────────────────────
    ("GET", "/api/dashboard/remediation"),
    ("GET", "/api/dashboard/vulnerabilities"),
    # ── CVE detail (api/routers/cve.py) ──────────────────────────────────────
    ("GET", "/api/dashboard/cves"),
    ("GET", "/api/dashboard/cves/{cve_id}"),
    # ── RAG documents / knowledge-store browser (api/routers/documents.py) ──
    ("GET", "/api/dashboard/documents"),
    ("GET", "/api/dashboard/documents/{document_id}"),
    # ── Phase 4 state-backend REST counterparts (api/routers/state_backend.py) ──
    ("GET", "/api/dashboard/environment-notes"),
    ("POST", "/api/dashboard/environment-notes"),
    ("POST", "/api/dashboard/environment-notes/{note_id}/resolve"),
    ("GET", "/api/dashboard/instincts/{instinct_id}/history"),
    ("POST", "/api/dashboard/instincts/propose"),
    ("POST", "/api/dashboard/documents"),
    # ── infra-ops hook write path (api/routers/internal_state.py, P5.1/P5.2) ──
    ("POST", "/api/internal/state/observations"),
    ("GET", "/api/internal/state/observations"),
    ("POST", "/api/internal/state/client-state"),
    ("GET", "/api/internal/state/client-state"),
    ("POST", "/api/internal/state/governance-events"),
    ("GET", "/api/internal/state/governance-events"),
    ("GET", "/api/internal/state/environment-notes"),
    # ── Governance (api/routers/governance.py) ────────────────────────────────
    ("GET", "/api/dashboard/activity"),
    ("GET", "/api/dashboard/agent-config"),
    ("GET", "/api/dashboard/agents"),
    ("GET", "/api/dashboard/audit_log"),
    ("GET", "/api/dashboard/compliance"),
    ("GET", "/api/dashboard/decisions"),
    ("GET", "/api/dashboard/drift_events"),
    ("GET", "/api/dashboard/drift_events/domains"),
    ("GET", "/api/dashboard/drift_events/trend"),
    ("GET", "/api/dashboard/generated_scripts"),
    # T7 (rev14) — LLM observability audit surface (llm_observability.py).
    ("GET", "/api/dashboard/llm/runs"),
    ("GET", "/api/dashboard/llm/runs/{run_id}"),
    ("GET", "/api/dashboard/llm/summary"),
    ("GET", "/api/dashboard/instincts"),
    ("GET", "/api/dashboard/integration_proposals"),
    ("GET", "/api/dashboard/inventory_reconcile"),
    ("GET", "/api/dashboard/notifications"),
    ("GET", "/api/dashboard/observations"),
    ("GET", "/api/dashboard/settings"),
    # TRK-321: narrow non-sensitive subset of the (now admin-only) settings dump
    ("GET", "/api/dashboard/settings/ui"),
    ("POST", "/api/dashboard/actions/{action_id}/approve"),
    ("POST", "/api/dashboard/actions/{action_id}/reject"),
    # #93: CoverageAgent proposal approve/reject (governance_intelligence.py)
    ("POST", "/api/dashboard/integration_proposals/{proposal_id}/approve"),
    ("POST", "/api/dashboard/integration_proposals/{proposal_id}/reject"),
    # ── UI / Chat / Custom Views (api/routers/ui.py) ─────────────────────────
    ("DELETE", "/api/dashboard/views/{view_id}"),
    ("GET", "/api/dashboard/views"),
    ("GET", "/api/dashboard/views/{share_token}"),
    ("PATCH", "/api/dashboard/views/{view_id}"),
    ("POST", "/api/dashboard/chat"),
    ("POST", "/api/dashboard/custom-view"),
    ("POST", "/api/dashboard/views"),
    # ── IaC / Pipelines (api/routers/iac.py) ─────────────────────────────────
    ("GET", "/api/iac/overview"),
    ("GET", "/api/iac/compose-services"),
    ("GET", "/api/iac/k8s-resources"),
    ("GET", "/api/iac/terraform-resources"),
    ("GET", "/api/iac/ansible"),
    ("GET", "/api/iac/ci-schedules"),
    # ── vSphere (api/routers/vsphere.py) ─────────────────────────────────────
    ("GET", "/api/vsphere/overview"),
    ("GET", "/api/vsphere/secondary"),
    # ── Cloud / K8s / Net (api/routers/cloudnet.py) — POC-disabled domains ───
    ("GET", "/api/cloudnet/overview"),
    # ── Knowledge graph (graph_api.py) ────────────────────────────────────────
    # Graph-first P5 removed /relationships, /search and the /{resource_id}
    # ego-network along with the resource_relationships store they read.
    # /stats kept its PATH (the question it answers has no id space in it) and
    # is now served from graph_edges; /kg/edges is /relationships' honestly-
    # renamed replacement in the graph_nodes id space.
    ("GET", "/api/graph/stats"),
    ("GET", "/api/graph/blast-radius/{node_id}"),  # TRK-204
    ("GET", "/api/graph/kg/stats"),
    ("GET", "/api/graph/kg/search"),
    ("GET", "/api/graph/kg/edges"),
    ("GET", "/api/graph/kg/{node_id}"),
    ("GET", "/api/graph/entity-resolution/queue"),  # TRK-227
    ("POST", "/api/graph/entity-resolution/{action_id}/confirm"),  # TRK-227
    ("POST", "/api/graph/entity-resolution/{action_id}/reject"),  # KG-3
    ("POST", "/api/graph/entity-resolution/{action_id}/retract"),  # TRK-228
}


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


def test_route_parity():
    """The app must expose exactly the routes in EXPECTED_ROUTES — no more, no less."""
    app = create_app()
    collected = _collect_routes(app.router)

    # Tripwire: if the collection helper breaks (e.g. FastAPI changes its internal
    # wrapper shape), it might silently return a partial set.  A shrunken
    # EXPECTED_ROUTES would then pass while hiding real route losses.  This floor
    # catches that failure mode and turns it into a loud error.
    assert len(collected) >= 70, (
        f"_collect_routes returned only {len(collected)} routes — expected at least 70. "
        "This likely means the collection helper is broken (FastAPI internal structure "
        "changed), not that routes were intentionally removed."
    )

    actual = set(collected)

    missing = EXPECTED_ROUTES - actual
    extra = actual - EXPECTED_ROUTES

    assert not missing, (
        f"Routes present in EXPECTED_ROUTES but MISSING from the app "
        f"({len(missing)}):\n" + "\n".join(f"  {m} {p}" for m, p in sorted(missing))
    )
    assert not extra, (
        f"Routes present in the app but NOT in EXPECTED_ROUTES "
        f"({len(extra)}):\n" + "\n".join(f"  {m} {p}" for m, p in sorted(extra))
    )


def test_no_duplicate_routes():
    """No (method, path) pair should be mounted more than once."""
    app = create_app()
    routes = _collect_routes(app.router)

    counts = Counter(routes)
    duplicates = {k: v for k, v in counts.items() if v > 1}

    assert not duplicates, (
        f"Duplicate route mounts detected ({len(duplicates)} pairs):\n"
        + "\n".join(f"  {m} {p} x{n}" for (m, p), n in sorted(duplicates.items()))
    )
