"""Fleet digest — a deterministic summary of current infra state.

Aggregates the headline numbers (open drift, prioritized CVEs, overdue EOL,
compliance violations, failed collections) into a markdown summary suitable for
a daily Confluence page or Jira/Slack digest.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone

from infra_brain.db.models import (
    ComplianceViolation,
    DriftEvent,
    EolRegistry,
    VulnQueueItem,
)
from infra_brain.db.session import get_session

logger = logging.getLogger(__name__)


def build_digest_markdown(now: datetime | None = None) -> str:
    now = now or datetime.now(timezone.utc)
    with get_session() as s:
        open_drift = s.query(DriftEvent).filter(DriftEvent.status == "open").count()
        open_vulns = (
            s.query(VulnQueueItem).filter(VulnQueueItem.status.in_(("open", "triage"))).count()
        )
        crit_vulns = (
            s.query(VulnQueueItem)
            .filter(
                VulnQueueItem.status.in_(("open", "triage")), VulnQueueItem.severity == "critical"
            )
            .count()
        )
        eol_overdue = 0
        for (eol_date,) in s.query(EolRegistry.eol_date).all():
            if (
                eol_date
                and (eol_date if eol_date.tzinfo else eol_date.replace(tzinfo=timezone.utc)) < now
            ):
                eol_overdue += 1
        violations = (
            s.query(ComplianceViolation).filter(ComplianceViolation.status == "open").count()
        )
    return (
        f"# Infra Brain — Fleet Digest ({now.date()})\n\n"
        f"| Metric | Count |\n|---|---|\n"
        f"| Open drift events | {open_drift} |\n"
        f"| Open vulnerabilities | {open_vulns} (critical: {crit_vulns}) |\n"
        f"| EOL assets overdue | {eol_overdue} |\n"
        f"| Open compliance violations | {violations} |\n\n"
        f"_Auto-generated by Infra Brain._\n"
    )


def post_digest() -> str:
    """Build the digest and publish it to Confluence (best-effort, gated + audited).

    The Confluence write flows through gate_external_write() inside
    upsert_confluence_page(), so a DLP hit is refused before any HTTP call and
    recorded in agent_action_log. Failures are LOGGED (never silently passed).
    """
    md = build_digest_markdown()
    try:
        from infra_brain.tools.confluence import upsert_confluence_page

        upsert_confluence_page("digest", "Infra Brain — Fleet Digest", md)
    except PermissionError:
        # Write-gate denial — content never left the process. Loud by design.
        logger.warning("digest: Confluence publish BLOCKED by write gate", exc_info=True)
    except Exception:  # noqa: BLE001 — digest publish is best-effort
        logger.warning("digest: Confluence publish failed", exc_info=True)
    return md
