"""Add CollectionRun.sweep_id (Phase 2 Task 1 sweep groundwork).

Revision ID: 71b2903db8d9
Revises: f3a1c2b4d5e6
Create Date: 2026-07-11

Hand-written (not autogenerated): no live Postgres instance was reachable in
this environment to run ``alembic revision --autogenerate``. This migration
was written to match the model change verbatim instead:

    CollectionRun.sweep_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        nullable=True, index=True
    )

Nullable, no default — a pure additive column, safe on any existing table
size. The index is a plain (non-unique, non-CONCURRENTLY) B-tree: the
``collection_runs`` table is small (one row per collection dispatch across
~28 domains), so a blocking index build here is not a production concern —
consistent with how prior migrations in this chain (e.g. 0027) treat this
same table.

Guarded with inspector existence checks (the same idempotency pattern 0032
documents): ``tests/test_migration_zone.py`` builds its live-volume fixture
via ``Base.metadata.create_all`` FIRST (so ``sweep_id`` already exists, from
the model) and then replays the migration chain from an old stamped head —
without the guard, ``upgrade()`` would try to add a column that is already
there and fail with "duplicate column name".
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = "71b2903db8d9"
down_revision = "f3a1c2b4d5e6"
branch_labels = None
depends_on = None

_TABLE = "collection_runs"
_COLUMN = "sweep_id"
_INDEX = "ix_collection_runs_sweep_id"


def upgrade() -> None:
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = {c["name"] for c in inspector.get_columns(_TABLE)}
    if _COLUMN not in columns:
        op.add_column(_TABLE, sa.Column(_COLUMN, sa.Uuid(), nullable=True))

    indexes = {ix["name"] for ix in inspector.get_indexes(_TABLE)}
    if _INDEX not in indexes:
        op.create_index(_INDEX, _TABLE, [_COLUMN], unique=False)


def downgrade() -> None:
    bind = op.get_bind()
    inspector = inspect(bind)
    indexes = {ix["name"] for ix in inspector.get_indexes(_TABLE)}
    if _INDEX in indexes:
        op.drop_index(_INDEX, table_name=_TABLE)

    columns = {c["name"] for c in inspector.get_columns(_TABLE)}
    if _COLUMN in columns:
        op.drop_column(_TABLE, _COLUMN)
