"""Add ProposedAction.thread_id/interrupt_id/graph_version (Phase 3 Task 1
reasoner groundwork).

Revision ID: 00cb512bde05
Revises: 71b2903db8d9
Create Date: 2026-07-12

Hand-written (not autogenerated): no live Postgres instance was reachable in
this environment to run ``alembic revision --autogenerate``, same situation
as 0033. Written to match the model change verbatim instead:

    thread_id: Mapped[Optional[str]] = mapped_column(String(128), nullable=True)
    interrupt_id: Mapped[Optional[str]] = mapped_column(String(128), nullable=True)
    graph_version: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)

All three columns are nullable with no default — a pure additive change,
safe on any existing table size (``proposed_actions`` is small: one row per
human-gated action proposal). ``thread_id`` gets an index because Task 5's
retention-protection query needs to efficiently find every ProposedAction
tied to a live LangGraph thread before that thread is pruned;
``interrupt_id``/``graph_version`` are plain metadata with no query-shape
requirement, so no index for those two — chosen over a payload-JSONB blob
for exactly this reason (JSONB can't be cheaply indexed the same way).

Guarded with inspector existence checks, same idempotency pattern as 0032/
0033: ``tests/test_migration_zone.py`` builds its live-volume fixture via
``Base.metadata.create_all`` FIRST (so these columns already exist, from the
model) and then replays the migration chain from an old stamped head —
without the guard, ``upgrade()`` would try to add columns that are already
there and fail with "duplicate column name".
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = "00cb512bde05"
down_revision = "71b2903db8d9"
branch_labels = None
depends_on = None

_TABLE = "proposed_actions"
_COLUMNS = {
    "thread_id": sa.String(length=128),
    "interrupt_id": sa.String(length=128),
    "graph_version": sa.String(length=64),
}
_INDEX = "ix_proposed_actions_thread_id"
_INDEX_COLUMN = "thread_id"


def upgrade() -> None:
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_columns = {c["name"] for c in inspector.get_columns(_TABLE)}
    for name, coltype in _COLUMNS.items():
        if name not in existing_columns:
            op.add_column(_TABLE, sa.Column(name, coltype, nullable=True))

    indexes = {ix["name"] for ix in inspector.get_indexes(_TABLE)}
    if _INDEX not in indexes:
        op.create_index(_INDEX, _TABLE, [_INDEX_COLUMN], unique=False)


def downgrade() -> None:
    bind = op.get_bind()
    inspector = inspect(bind)
    indexes = {ix["name"] for ix in inspector.get_indexes(_TABLE)}
    if _INDEX in indexes:
        op.drop_index(_INDEX, table_name=_TABLE)

    existing_columns = {c["name"] for c in inspector.get_columns(_TABLE)}
    for name in _COLUMNS:
        if name in existing_columns:
            op.drop_column(_TABLE, name)
