"""graph edge authority, host identity ambiguity, kg9 identity fk indexes

Revision ID: 005f5781df29
Revises: 1ea7fa6eb94d
Create Date: 2026-08-10 19:26:04.252076

Autogenerated, then hand-hardened in exactly two places. Both are recorded here
because the repo's standing rule is that migrations are generated, not written,
so any deviation needs to justify itself.

1. ``ck_graph_edges_authority`` is ADDED BY HAND (autogenerate omitted it).
   ``GraphEdge`` declares a table-level ``CheckConstraint("authority IN
   ('auto','human')")``, but Alembic's autogenerate does not emit table-level
   CHECK constraints, and — worse — ``alembic check`` does not detect their
   absence either, so this migration reported "No new upgrade operations
   detected" while silently leaving the constraint off the database.
   That matters here specifically: the local suite runs on sqlite via
   ``Base.metadata.create_all()``, which DOES create the constraint. Without
   this hand-added op, every test would enforce the authority enum while
   PostgreSQL did not — a green suite over an unenforced production
   constraint, which is the exact test/prod divergence class the three hard MR
   gates exist to catch. `authority` is the discriminator the whole KG-1 fix
   rests on (an automatic emitter must not overwrite a human decision); it is
   not a field to leave unconstrained in the only database that matters.

2. Indexes are created NON-concurrently, deliberately. The project rule calls
   for ``postgresql_concurrently=True`` on large or actively-written tables
   (resources, snapshots, drift_events, vuln_queue, eol_registry).
   ``host_identities`` is neither: it currently holds 7 rows, one per fleet
   host, and grows with the fleet, not with time. A plain CREATE INDEX takes a
   sub-millisecond SHARE lock there — which blocks writes, NOT reads; that is
   the thing CONCURRENTLY exists to avoid, and it is what makes the size of the
   table the deciding factor. CONCURRENTLY cannot run inside
   a transaction and would require an ``autocommit_block()`` — losing this
   migration's transactional all-or-nothing property, and leaving INVALID
   indexes behind on failure — to protect against a lock that is already
   negligible. Revisit if host_identities ever becomes per-observation rather
   than per-host.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '005f5781df29'
down_revision: Union[str, Sequence[str], None] = '1ea7fa6eb94d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('graph_edges', sa.Column('authority', sa.String(length=16), server_default='auto', nullable=False))
    op.add_column('host_identities', sa.Column('identity_ambiguous_sources', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.create_index(op.f('ix_host_identities_cloud_resource_id'), 'host_identities', ['cloud_resource_id'], unique=False)
    op.create_index(op.f('ix_host_identities_k8s_resource_id'), 'host_identities', ['k8s_resource_id'], unique=False)
    op.create_index(op.f('ix_host_identities_linux_resource_id'), 'host_identities', ['linux_resource_id'], unique=False)
    op.create_index(op.f('ix_host_identities_net_resource_id'), 'host_identities', ['net_resource_id'], unique=False)
    op.create_index(op.f('ix_host_identities_netdevice_resource_id'), 'host_identities', ['netdevice_resource_id'], unique=False)
    op.create_index(op.f('ix_host_identities_octopus_resource_id'), 'host_identities', ['octopus_resource_id'], unique=False)
    op.create_index(op.f('ix_host_identities_r7_resource_id'), 'host_identities', ['r7_resource_id'], unique=False)
    op.create_index(op.f('ix_host_identities_vsphere_resource_id'), 'host_identities', ['vsphere_resource_id'], unique=False)
    op.create_index(op.f('ix_host_identities_windows_resource_id'), 'host_identities', ['windows_resource_id'], unique=False)
    # ### end Alembic commands ###

    # Hand-added — see reason 1 in the module docstring. Autogenerate does not
    # emit table-level CHECK constraints and `alembic check` does not miss them,
    # so without this the model claims an enforcement PostgreSQL never had.
    op.create_check_constraint(
        "ck_graph_edges_authority", "graph_edges", "authority IN ('auto', 'human')"
    )


def downgrade() -> None:
    """Downgrade schema.

    Drops the authority column, so every edge's human-vs-auto provenance is
    lost — irreversibly. That is inherent to reverting the column, not an
    oversight: there is nowhere else that fact is stored. Downgrading past this
    revision on a database where operators have confirmed identity matches
    means those confirmations become indistinguishable from machine output.
    """
    op.drop_constraint("ck_graph_edges_authority", "graph_edges", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_host_identities_windows_resource_id'), table_name='host_identities')
    op.drop_index(op.f('ix_host_identities_vsphere_resource_id'), table_name='host_identities')
    op.drop_index(op.f('ix_host_identities_r7_resource_id'), table_name='host_identities')
    op.drop_index(op.f('ix_host_identities_octopus_resource_id'), table_name='host_identities')
    op.drop_index(op.f('ix_host_identities_netdevice_resource_id'), table_name='host_identities')
    op.drop_index(op.f('ix_host_identities_net_resource_id'), table_name='host_identities')
    op.drop_index(op.f('ix_host_identities_linux_resource_id'), table_name='host_identities')
    op.drop_index(op.f('ix_host_identities_k8s_resource_id'), table_name='host_identities')
    op.drop_index(op.f('ix_host_identities_cloud_resource_id'), table_name='host_identities')
    op.drop_column('host_identities', 'identity_ambiguous_sources')
    op.drop_column('graph_edges', 'authority')
    # ### end Alembic commands ###
