"""add last_seen_at and dedup_key to drift_events

Revision ID: 1dbf38e28aa6
Revises: ff31bf0c5491
Create Date: 2026-07-31 11:06:47.912126

GitLab #163 + #164 land the SAME schema change on ``drift_events``, so they share
one migration rather than racing two:

  * ``last_seen_at`` (nullable timestamptz) — bumped on every sweep that
    RE-OBSERVES an already-open finding, so ``detected_at`` can finally stay
    immutable at first observation. Nullable by construction: pre-existing rows
    have no re-observation history, which is why every recency-sorted reader must
    use ``coalesce(last_seen_at, detected_at)``.
  * ``dedup_key`` (nullable varchar(256), indexed) — a queryable, indexable dedup
    identity for findings whose natural key otherwise lives inside the
    ``new_value`` JSONB blob (the IaC secret scanner's (secret_type, file_path)
    pair). Nullable: writers that already dedup on real columns leave it unset.
  * ``drift_type`` widened VARCHAR(32) -> VARCHAR(64) — #163 splits the flat
    ``identity_conflict`` type into ``identity_conflict_suffix_variant`` (32) and
    ``identity_conflict_distinct_object`` (33), which VARCHAR(32) rejects on
    PostgreSQL. Widening a varchar is a catalog-only change: no table rewrite, no
    backfill, and every existing value stays valid.

Hand-adjustments to the autogenerated body (the template's own "please adjust!"),
each load-bearing:

  1. INSPECTOR GUARDS. ``0001_initial_schema`` seeds a fresh database via
     ``Base.metadata.create_all()`` against the LIVE ORM metadata, so on any
     from-nothing upgrade (the `migration-parity` CI gate, tests/test_migration.py)
     drift_events ALREADY has both columns and the index by the time this revision
     runs. Un-guarded ``op.add_column`` would raise DuplicateColumn and break
     `alembic upgrade head` on every fresh DB. Mirrors 0005/0006/0007/0008.
  2. CONCURRENTLY. ``drift_events`` is continuously written by every collector's
     drift phase; a plain CREATE INDEX takes ACCESS EXCLUSIVE for the build's
     duration and would block live collection runs. Built inside an
     ``autocommit_block()`` because CREATE INDEX CONCURRENTLY cannot run inside a
     transaction.
  3. DIALECT GUARD on the type change. sqlite has no ALTER COLUMN TYPE (it needs
     batch mode); the widening is a PostgreSQL-only concern because sqlite does
     not enforce VARCHAR lengths at all.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = "1dbf38e28aa6"
down_revision: Union[str, Sequence[str], None] = "ff31bf0c5491"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_INDEX_NAME = "ix_drift_events_dedup_key"


def _drift_event_columns(bind) -> set[str]:
    return {c["name"] for c in inspect(bind).get_columns("drift_events")}


def _drift_event_indexes(bind) -> set[str]:
    return {i["name"] for i in inspect(bind).get_indexes("drift_events")}


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    is_pg = bind.dialect.name == "postgresql"
    cols = _drift_event_columns(bind)

    if "last_seen_at" not in cols:
        op.add_column(
            "drift_events", sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True)
        )
    if "dedup_key" not in cols:
        op.add_column("drift_events", sa.Column("dedup_key", sa.String(length=256), nullable=True))

    if is_pg:
        # Idempotent: already-64 -> catalog no-op. Nullability is unchanged.
        op.alter_column(
            "drift_events",
            "drift_type",
            existing_type=sa.VARCHAR(length=32),
            type_=sa.String(length=64),
            existing_nullable=False,
        )

    if _INDEX_NAME not in _drift_event_indexes(bind):
        if is_pg:
            with op.get_context().autocommit_block():
                op.create_index(
                    _INDEX_NAME,
                    "drift_events",
                    ["dedup_key"],
                    unique=False,
                    postgresql_concurrently=True,
                )
        else:
            op.create_index(_INDEX_NAME, "drift_events", ["dedup_key"], unique=False)


def downgrade() -> None:
    """Downgrade schema.

    DATA LOSS, by design and bounded: dropping ``last_seen_at``/``dedup_key``
    discards re-observation timestamps and dedup identities. Nothing else derives
    from them — ``detected_at`` (the immutable first-observation stamp) and the
    JSONB ``new_value`` payload both survive, so the pre-#163/#164 readers keep
    working on the downgraded schema. Narrowing ``drift_type`` back to VARCHAR(32)
    would REJECT any row written with the new sub-classed identity-conflict types,
    so it is done last and only after those rows would already have been removed
    by the drop of the feature that writes them.

    LOCK NOTE (downgrade only): unlike the WIDENING in ``upgrade()``, which is
    catalog-only, NARROWING a varchar makes PostgreSQL scan every remaining row
    to confirm it fits — holding ACCESS EXCLUSIVE for the scan's duration on a
    continuously-written table. The ``DELETE`` above bounds correctness, not lock
    time. Acceptable because this is the rare/emergency path and ``env.py``'s
    ``lock_timeout = '4s'`` turns contention into a loud failure rather than a
    hang, but do not assume this step is as cheap as its upgrade counterpart.
    """
    bind = op.get_bind()
    is_pg = bind.dialect.name == "postgresql"

    if _INDEX_NAME in _drift_event_indexes(bind):
        if is_pg:
            with op.get_context().autocommit_block():
                op.drop_index(_INDEX_NAME, table_name="drift_events", postgresql_concurrently=True)
        else:
            op.drop_index(_INDEX_NAME, table_name="drift_events")

    cols = _drift_event_columns(bind)
    if "dedup_key" in cols:
        op.drop_column("drift_events", "dedup_key")
    if "last_seen_at" in cols:
        op.drop_column("drift_events", "last_seen_at")

    if is_pg:
        op.execute(
            "DELETE FROM drift_events WHERE drift_type IN "
            "('identity_conflict_suffix_variant', 'identity_conflict_distinct_object')"
        )
        op.alter_column(
            "drift_events",
            "drift_type",
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(length=32),
            existing_nullable=False,
        )
