"""reconcile migrated schema with models (TRK-312 followup)

Revision ID: 1ea7fa6eb94d
Revises: 97383c02a97a
Create Date: 2026-08-08 05:50:44.060192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ea7fa6eb94d'
down_revision: Union[str, Sequence[str], None] = '97383c02a97a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



# ---------------------------------------------------------------------------
# Baseline-safety helpers (hand-added to the autogenerated body).
#
# This revision was autogenerated against a database built by replaying the
# migration chain from empty. It will ALSO run against the long-lived
# deployment, whose schema was built through the pre-TRK-312 blanket
# Base.metadata.create_all() path. Those two baselines have genuinely
# diverged: all six unique constraints dropped below exist on a chain-replayed
# DB and do NOT exist on the live one (verified directly against production —
# pg_constraint returned 0 rows for every name). A bare op.drop_constraint()
# aborts the whole migration on a missing constraint, which would have killed
# the deploy's migrate container.
#
# Dropping IF EXISTS makes each step converge to the same end state from
# either baseline, which is the only property that actually matters here.
# ---------------------------------------------------------------------------
def _drop_constraint_if_exists(table: str, name: str) -> None:
    op.execute(f'ALTER TABLE {table} DROP CONSTRAINT IF EXISTS {name}')


def _drop_index_if_exists(name: str) -> None:
    op.execute(f'DROP INDEX IF EXISTS {name}')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_config_settings', 'value',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('agent_config_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ansible_playbook_plays', 'play_index',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ansible_playbook_plays', 'hosts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('ci_schedules', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ci_schedules', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('ci_schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('ci_schedules', 'collected_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('compose_services', 'ports',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('gitlab_projects', 'archived',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    _drop_constraint_if_exists('gitlab_projects', 'uq_gitlab_project_id')
    _drop_index_if_exists('ix_gitlab_projects_gitlab_project_id')
    op.create_index(op.f('ix_gitlab_projects_gitlab_project_id'), 'gitlab_projects', ['gitlab_project_id'], unique=True)
    op.alter_column('host_identities', 'ip_addresses',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('iac_files', 'size_bytes',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('k8s_nodes', 'roles',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('octopus_channels', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('octopus_environments', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('octopus_lifecycles', 'phases',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('octopus_machines', 'is_disabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('octopus_machines', 'roles',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('octopus_machines', 'environment_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('octopus_machines', 'environment_names',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('octopus_projects', 'is_disabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('r7_assets', 'vuln_critical',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('r7_assets', 'vuln_severe',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('r7_assets', 'vuln_moderate',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('r7_assets', 'vuln_total',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('r7_assets', 'vuln_exploits',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('r7_assets', 'vuln_malware_kits',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('r7_assets', 'assessed_for_vulnerabilities',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    _drop_constraint_if_exists('r7_assets', 'uq_r7_asset_natkey')
    _drop_constraint_if_exists('r7_sites', 'uq_r7_site_natkey')
    _drop_constraint_if_exists('r7_solutions', 'uq_r7_solution_natkey')
    _drop_constraint_if_exists('r7_tags', 'uq_r7_tag_natkey')
    op.alter_column('r7_vulnerabilities', 'exploits',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('r7_vulnerabilities', 'malware_kits',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('r7_vulnerabilities', 'categories',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('r7_vulnerabilities', 'cves',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    _drop_constraint_if_exists('r7_vulnerabilities', 'uq_r7_vulnerability_natkey')
    op.alter_column('resource_relationships', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('resource_relationships', 'last_seen',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('vsphere_clusters', 'host_names',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('vsphere_clusters', 'datastore_names',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('vsphere_hosts', 'datastore_names',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('vsphere_vms', 'is_template',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('vsphere_vms', 'all_ips',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('vsphere_vms', 'datastore_names',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('vsphere_vms', 'network_names',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('windows_services', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('windows_services', 'collected_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('windows_software', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('windows_software', 'collected_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('windows_software', 'collected_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('windows_software', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('windows_services', 'collected_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('windows_services', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('vsphere_vms', 'network_names',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('vsphere_vms', 'datastore_names',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('vsphere_vms', 'all_ips',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('vsphere_vms', 'is_template',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('vsphere_hosts', 'datastore_names',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('vsphere_clusters', 'datastore_names',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('vsphere_clusters', 'host_names',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('resource_relationships', 'last_seen',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('resource_relationships', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint(op.f('uq_r7_vulnerability_natkey'), 'r7_vulnerabilities', ['r7_vuln_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('r7_vulnerabilities', 'cves',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('r7_vulnerabilities', 'categories',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('r7_vulnerabilities', 'malware_kits',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('r7_vulnerabilities', 'exploits',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq_r7_tag_natkey'), 'r7_tags', ['r7_tag_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_r7_solution_natkey'), 'r7_solutions', ['r7_solution_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_r7_site_natkey'), 'r7_sites', ['r7_site_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_r7_asset_natkey'), 'r7_assets', ['r7_asset_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('r7_assets', 'assessed_for_vulnerabilities',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('r7_assets', 'vuln_malware_kits',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('r7_assets', 'vuln_exploits',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('r7_assets', 'vuln_total',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('r7_assets', 'vuln_moderate',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('r7_assets', 'vuln_severe',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('r7_assets', 'vuln_critical',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('octopus_projects', 'is_disabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('octopus_machines', 'environment_names',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('octopus_machines', 'environment_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('octopus_machines', 'roles',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('octopus_machines', 'is_disabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('octopus_lifecycles', 'phases',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('octopus_environments', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('octopus_channels', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('k8s_nodes', 'roles',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('iac_files', 'size_bytes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('host_identities', 'ip_addresses',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               existing_nullable=False)
    _drop_index_if_exists('ix_gitlab_projects_gitlab_project_id')
    op.create_index(op.f('ix_gitlab_projects_gitlab_project_id'), 'gitlab_projects', ['gitlab_project_id'], unique=False)
    op.create_unique_constraint(op.f('uq_gitlab_project_id'), 'gitlab_projects', ['gitlab_project_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('gitlab_projects', 'archived',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('compose_services', 'ports',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('ci_schedules', 'collected_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('ci_schedules', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('ci_schedules', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('ci_schedules', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('ansible_playbook_plays', 'hosts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('ansible_playbook_plays', 'play_index',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('agent_config_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('agent_config_settings', 'value',
               existing_type=sa.TEXT(),
               server_default=sa.text("''::text"),
               existing_nullable=False)
    # ### end Alembic commands ###
