"""trk160_mcp_api_key_expires_at

Add the optional ``expires_at`` column to ``mcp_api_keys`` (TRK-160). NULL means
"never expires", so every key that exists at the moment this runs keeps working
with identical behavior — the column changes nothing until someone mints a key
with an expiry. Enforcement lives in ``mcp_auth.lookup_active_key``, alongside
the existing ``revoked_at`` check; this migration only makes the column exist.

Danger-pattern review (per /migration-create step 2):
  * NOT NULL without default — N/A. The column is nullable with no default, so
    PostgreSQL records a catalog-only change: no table rewrite, no backfill, and
    the ACCESS EXCLUSIVE lock is held for microseconds. ``mcp_api_keys`` is a
    tiny, rarely-written table regardless.
  * DROP TABLE / DROP COLUMN — none in ``upgrade()``. ``downgrade()`` drops the
    column it added, which is the correct inverse; the only data lost on a
    downgrade is the expiry timestamps themselves, after which every key reverts
    to never-expiring. That is a security-relevant (keys become immortal again),
    not a correctness-relevant, loss — deliberate and acceptable for a rollback.
  * Index creation — none, so ``CONCURRENTLY`` does not apply. No index is
    warranted: ``expires_at`` is never a query predicate. It is read only off a
    row already fetched by the unique-indexed ``token_hash``, and filtered in
    Python (see the timezone rationale in ``mcp_auth.lookup_active_key``).
  * lock_timeout — already set globally to 4s by ``alembic/env.py`` inside
    alembic's transaction block; nothing to add per-migration.
  * Single head — verified: this revises 95d988b2bc3c, the sole prior head.

Revision ID: 69a24298167a
Revises: 95d988b2bc3c
Create Date: 2026-08-13 14:34:24.607811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69a24298167a'
down_revision: Union[str, Sequence[str], None] = '95d988b2bc3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_api_keys', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcp_api_keys', 'expires_at')
    # ### end Alembic commands ###
