"""vsphere_phaseD_cluster_drs_evc

Revision ID: 7af94c999f92
Revises: 808138e3c101
Create Date: 2026-07-13 18:18:13.888429

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7af94c999f92"
down_revision: Union[str, Sequence[str], None] = "808138e3c101"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Guards add_column calls with a column existence check: migrations 0002/0003/0014
    call Base.metadata.create_all() with no table filter, pre-creating vsphere_clusters
    with the current model on a fresh DB — which already includes these columns.
    """
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_cols_clusters = {col["name"] for col in inspector.get_columns("vsphere_clusters")}
    if "evc_mode" not in existing_cols_clusters:
        op.add_column(
            "vsphere_clusters", sa.Column("evc_mode", sa.String(length=64), nullable=True)
        )
        op.add_column(
            "vsphere_clusters", sa.Column("ha_admission_control", sa.Boolean(), nullable=True)
        )
        op.add_column(
            "vsphere_clusters",
            sa.Column(
                "drs_rules",
                sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
                nullable=True,
            ),
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vsphere_clusters", "drs_rules")
    op.drop_column("vsphere_clusters", "ha_admission_control")
    op.drop_column("vsphere_clusters", "evc_mode")
    # ### end Alembic commands ###
