"""vsphere_phaseC_host_hardening

Revision ID: 808138e3c101
Revises: eeda3039b7b1
Create Date: 2026-07-13 18:12:06.885912

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "808138e3c101"
down_revision: Union[str, Sequence[str], None] = "eeda3039b7b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Guards add_column calls with a column existence check: migrations 0002/0003/0014
    call Base.metadata.create_all() with no table filter, pre-creating vsphere_hosts
    with the current model on a fresh DB — which already includes these columns.
    """
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_cols_hosts = {col["name"] for col in inspector.get_columns("vsphere_hosts")}
    if "ntp_servers" not in existing_cols_hosts:
        op.add_column(
            "vsphere_hosts",
            sa.Column(
                "ntp_servers",
                sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
                nullable=True,
            ),
        )
        op.add_column(
            "vsphere_hosts", sa.Column("syslog_host", sa.String(length=256), nullable=True)
        )
        op.add_column(
            "vsphere_hosts", sa.Column("lockdown_mode", sa.String(length=32), nullable=True)
        )
        op.add_column("vsphere_hosts", sa.Column("ssh_enabled", sa.Boolean(), nullable=True))
        op.add_column("vsphere_hosts", sa.Column("esxi_shell_enabled", sa.Boolean(), nullable=True))
        op.add_column("vsphere_hosts", sa.Column("shell_timeout_sec", sa.Integer(), nullable=True))
        op.add_column(
            "vsphere_hosts", sa.Column("account_lock_failures", sa.Integer(), nullable=True)
        )
        op.add_column(
            "vsphere_hosts", sa.Column("bios_version", sa.String(length=64), nullable=True)
        )
        op.add_column(
            "vsphere_hosts", sa.Column("bios_date", sa.DateTime(timezone=True), nullable=True)
        )
        op.add_column("vsphere_hosts", sa.Column("hw_health", sa.String(length=16), nullable=True))
        op.add_column("vsphere_hosts", sa.Column("hw_health_issues", sa.Integer(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vsphere_hosts", "hw_health_issues")
    op.drop_column("vsphere_hosts", "hw_health")
    op.drop_column("vsphere_hosts", "bios_date")
    op.drop_column("vsphere_hosts", "bios_version")
    op.drop_column("vsphere_hosts", "account_lock_failures")
    op.drop_column("vsphere_hosts", "shell_timeout_sec")
    op.drop_column("vsphere_hosts", "esxi_shell_enabled")
    op.drop_column("vsphere_hosts", "ssh_enabled")
    op.drop_column("vsphere_hosts", "lockdown_mode")
    op.drop_column("vsphere_hosts", "syslog_host")
    op.drop_column("vsphere_hosts", "ntp_servers")
    # ### end Alembic commands ###
