"""phase4 state backend: environment_notes, instinct governance, client state, governance events, instinct/document extensions

Revision ID: 87ed7c6601d0
Revises: 1dbf38e28aa6
Create Date: 2026-08-01 00:57:14.587330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87ed7c6601d0'
down_revision: Union[str, Sequence[str], None] = '1dbf38e28aa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.String(length=128), nullable=False),
    sa.Column('agent', sa.String(length=64), nullable=False),
    sa.Column('tool', sa.String(length=128), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('event_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_client_observations_client_id', 'client_observations', ['client_id'], unique=False)
    op.create_index('ix_client_observations_created_at', 'client_observations', ['created_at'], unique=False)
    op.create_table('client_state_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('collection', sa.String(length=64), nullable=False),
    sa.Column('entry_id', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('client_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_client_state_entries_collection_client', 'client_state_entries', ['collection', 'client_id'], unique=False)
    op.create_index('ix_client_state_entries_collection_entry', 'client_state_entries', ['collection', 'entry_id'], unique=False)
    op.create_table('environment_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('resolved_by', sa.String(length=128), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('governance_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_governance_events_client_id', 'governance_events', ['client_id'], unique=False)
    op.create_index('ix_governance_events_created_at', 'governance_events', ['created_at'], unique=False)
    op.create_table('instinct_proposals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('zone', sa.String(length=32), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('pattern', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('citation', sa.Text(), nullable=True),
    sa.Column('proposed_by', sa.String(length=128), nullable=False),
    sa.Column('proposed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instinct_approvals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('instinct_id', sa.Uuid(), nullable=False),
    sa.Column('approved_by', sa.String(length=128), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['instinct_id'], ['instincts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instinct_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('instinct_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('changed_by', sa.String(length=128), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instinct_id'], ['instincts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # TRK-312: `documents` and `instincts` are owned by 0001, which seeds them
    # with Base.metadata.create_all() against the LIVE ORM metadata — so on a
    # fresh database they are created already carrying every column below, and
    # these bare add_column calls died with
    # DuplicateColumn: column "client_origin" of relation "documents" already
    # exists. Guarded per-column with the inspector, the same pattern 0015 and
    # 0022 already use. On a real deployment sitting at an earlier revision the
    # columns are genuinely absent and every add still runs.
    _insp = sa.inspect(op.get_bind())
    _existing: dict[str, set[str]] = {}

    def _add_column_if_missing(table: str, column: sa.Column) -> None:
        if table not in _existing:
            _existing[table] = {c["name"] for c in _insp.get_columns(table)}
        if column.name in _existing[table]:
            return
        op.add_column(table, column)
        _existing[table].add(column.name)

    _add_column_if_missing('documents', sa.Column('client_origin', sa.String(length=64), nullable=True))
    _add_column_if_missing('documents', sa.Column('ingested_by', sa.String(length=128), nullable=True))
    _add_column_if_missing('instincts', sa.Column('evidence', sa.Text(), nullable=True))
    _add_column_if_missing('instincts', sa.Column('evidence_summary', sa.String(length=512), nullable=True))
    _add_column_if_missing('instincts', sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False))
    _add_column_if_missing('instincts', sa.Column('status', sa.String(length=32), server_default=sa.text("'active'"), nullable=False))
    _add_column_if_missing('instincts', sa.Column('source', sa.String(length=128), nullable=True))
    _add_column_if_missing('instincts', sa.Column('proposed_by', sa.String(length=128), nullable=True))
    _add_column_if_missing('instincts', sa.Column('proposed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instincts', 'proposed_at')
    op.drop_column('instincts', 'proposed_by')
    op.drop_column('instincts', 'source')
    op.drop_column('instincts', 'status')
    op.drop_column('instincts', 'version')
    op.drop_column('instincts', 'evidence_summary')
    op.drop_column('instincts', 'evidence')
    op.drop_column('documents', 'ingested_by')
    op.drop_column('documents', 'client_origin')
    op.drop_table('instinct_versions')
    op.drop_table('instinct_approvals')
    op.drop_table('instinct_proposals')
    op.drop_index('ix_governance_events_created_at', table_name='governance_events')
    op.drop_index('ix_governance_events_client_id', table_name='governance_events')
    op.drop_table('governance_events')
    op.drop_table('environment_notes')
    op.drop_index('ix_client_state_entries_collection_entry', table_name='client_state_entries')
    op.drop_index('ix_client_state_entries_collection_client', table_name='client_state_entries')
    op.drop_table('client_state_entries')
    op.drop_index('ix_client_observations_created_at', table_name='client_observations')
    op.drop_index('ix_client_observations_client_id', table_name='client_observations')
    op.drop_table('client_observations')
    # ### end Alembic commands ###
