"""dns_zone_record_issue95

Revision ID: a4f6c8d1e2b3
Revises: 9d83fb71e295
Create Date: 2026-07-30 00:00:00.000000

New ``dns_zones`` / ``dns_records`` tables (GitLab issue #95): DNS
zone/record monitoring and drift detection. ``dns_zones`` is 1:1 with a
``domain="dns"`` ``Resource`` row (same pattern as ``LinuxHost``/
``VsphereVm``) and carries SOA/serial metadata; ``dns_records`` carries the
individual A/AAAA/CNAME/MX/TXT/SRV/NS records, natural-keyed on
``(zone_id, name, type, value)`` so DriftDetector can diff them like any
other domain's snapshots. Purely additive — no existing table, column,
constraint, or index is touched.

Hand-completed after autogenerate produced an empty diff, for the identical
documented reason as ``31e8b31f182f_trk_resource_ownership.py`` /
``ec4de4fefbef_graph_phase2_nodes_edges.py``: on a from-empty chain (CI's
migration-parity gate and the local reproduction run), ``0001_initial_schema``
runs a ``Base.metadata.create_all()`` scoped to whatever tables no *later*
migration file yet claims — and before this file existed, that scope
included ``dns_zones``/``dns_records``, so by the time a hypothetical
autogenerate ran the tables already existed and no diff was produced. The
``existing_tables`` inspector guard below is the same pattern; it also feeds
``0001_initial_schema._tables_owned_by_later_migrations()`` (which
regex-scans sibling migrations for the ``op.create_table("<table>"...)``
pattern), so 0001 now excludes both tables and this migration becomes the
one true owner of their DDL going forward.

Column types/nullability/defaults/indexes below were generated by inspecting
``Base.metadata.tables["dns_zones"|"dns_records"]`` directly (not
transcribed by hand) to guarantee they match ``db/models/dns.py`` exactly —
see the review notes in the accompanying MR/handoff for the inspection
command used.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = "a4f6c8d1e2b3"
down_revision: Union[str, Sequence[str], None] = "9d83fb71e295"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    existing_tables = set(inspect(op.get_bind()).get_table_names())

    if "dns_zones" not in existing_tables:
        op.create_table(
            "dns_zones",
            sa.Column("id", sa.Uuid(), nullable=False),
            sa.Column("resource_id", sa.Uuid(), nullable=False),
            sa.Column("name", sa.String(length=256), nullable=False),
            sa.Column("serial", sa.BigInteger(), nullable=True),
            sa.Column("primary_ns", sa.String(length=256), nullable=True),
            sa.Column("admin_email", sa.String(length=256), nullable=True),
            sa.Column("refresh_seconds", sa.Integer(), nullable=True),
            sa.Column("retry_seconds", sa.Integer(), nullable=True),
            sa.Column("expire_seconds", sa.Integer(), nullable=True),
            sa.Column("minimum_ttl_seconds", sa.Integer(), nullable=True),
            sa.Column("axfr_succeeded", sa.Boolean(), nullable=False),
            sa.Column("last_collected_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
            sa.ForeignKeyConstraint(["resource_id"], ["resources.id"]),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("resource_id", name="uq_dns_zones_resource_id"),
        )
        op.create_index(op.f("ix_dns_zones_name"), "dns_zones", ["name"], unique=False)

    if "dns_records" not in existing_tables:
        op.create_table(
            "dns_records",
            sa.Column("id", sa.Uuid(), nullable=False),
            sa.Column("zone_id", sa.Uuid(), nullable=False),
            sa.Column("name", sa.String(length=256), nullable=False),
            sa.Column("type", sa.String(length=16), nullable=False),
            sa.Column("value", sa.Text(), nullable=False),
            sa.Column("ttl", sa.Integer(), nullable=True),
            sa.Column("priority", sa.Integer(), nullable=True),
            sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
            sa.ForeignKeyConstraint(["zone_id"], ["dns_zones.id"]),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint(
                "zone_id", "name", "type", "value", name="uq_dns_record_natural_key"
            ),
        )
        op.create_index(op.f("ix_dns_records_name"), "dns_records", ["name"], unique=False)
        op.create_index(op.f("ix_dns_records_type"), "dns_records", ["type"], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f("ix_dns_records_type"), table_name="dns_records")
    op.drop_index(op.f("ix_dns_records_name"), table_name="dns_records")
    op.drop_table("dns_records")
    op.drop_index(op.f("ix_dns_zones_name"), table_name="dns_zones")
    op.drop_table("dns_zones")
