"""TRK-330: index the remaining unindexed FK-referencing columns.

Revision ID: adacc8308153
Revises: 74cd24313ffd
Create Date: 2026-08-11 00:18:21.866191

PostgreSQL does not index the referencing side of a foreign key automatically
(only the PK/UNIQUE side gets one) — every join from a detail table back to
its parent was a sequential scan until indexed explicitly. The nine
``host_identities.*_resource_id`` legs were already fixed under KG-9
(``005f5781df29``) and are NOT touched again here.

Autogenerated (via a scratch Postgres 15 container, never against the live
DB), then hand-adjusted in three ways, each explained below: (1) the
CONCURRENTLY/autocommit-block treatment autogenerate cannot express, (2)
inspector existence guards on every ``create_index`` call, and (3) dropping
10 of the 46 columns the naive audit script flagged because they are false
positives — already covered by an existing index.

1. WHY 36 COLUMNS, NOT 46
==========================
Regenerating the audit query against current ``db/models/`` prints exactly 46
FK-referencing columns with no ``index=True``/``unique=True`` and no
single-column ``Index``. But that query only counts a column as "indexed" if
it is the SOLE column of some index — it does not do leftmost-prefix
reasoning, so it misses that a composite (or even single-column) UNIQUE
index already covers a column when that column is the LEADING member. A
multi-column btree fully serves an equality lookup/join on just its leading
column(s) — PostgreSQL does not need a redundant dedicated index for that.
Cross-checked against ``pg_indexes`` on the live deployed DB (read-only;
no data or schema touched there) and each model's ``__table_args__``, the
following 10 are exactly that kind of false positive and get NO new index
here — adding one would be pure write-amplification with zero read benefit:

  * ``resource_ownership.resource_id`` — ``uq_resource_ownership_resource_id``
    is a single-column UNIQUE index on this column alone.
  * ``root_cause_notes.drift_event_id`` — ``uq_rootcause_drift``, same shape.
  * ``vuln_queue.resource_id`` — leading column of the composite UNIQUE
    ``ix_vuln_queue_resource_cve (resource_id, cve_id)`` (see 0008).
  * ``dns_records.zone_id`` — leading column of the composite UNIQUE
    ``uq_dns_record_natural_key (zone_id, name, type, value)``.
  * ``lb_pools.instance_id`` — leading column of
    ``uq_lb_pool_natkey (instance_id, name)``.
  * ``lb_pool_members.pool_id`` — leading column of
    ``uq_lb_pool_member_natkey (pool_id, address, port)``.
  * ``lb_virtual_servers.instance_id`` — leading column of
    ``uq_lb_virtual_server_natkey (instance_id, name)``.
  * ``linux_mounts.host_id`` — leading column of
    ``uq_linux_mount_natkey (host_id, mount)``.
  * ``linux_nics.host_id`` — leading column of
    ``uq_linux_nic_natkey (host_id, name)``.
  * ``linux_pending_updates.host_id`` — leading column of
    ``uq_linux_pending_update_natkey (host_id, package, available_version)``.

The remaining 36 columns (this migration's actual scope) genuinely have no
covering index of any shape. Blindly indexing all 46 because a linter
flagged them would have added 10 indexes that never earn back their write
cost — every INSERT/UPDATE into those 10 columns would maintain a second,
redundant btree for no query the planner would ever prefer over the
existing composite.

2. CONCURRENTLY vs PLAIN, PER TABLE (live row counts measured 2026-08-11
==========================================================================
against the deployed dev/pre-production Postgres, SELECT-only, via
``docker exec infra-brain-postgres-1 psql ... -c "select count(*) from
<table>"``):

CONCURRENTLY (22 columns) — built inside ``autocommit_block()`` because
CREATE INDEX CONCURRENTLY cannot run inside a transaction; this costs the
build its atomicity (a failed CONCURRENTLY build can leave an INVALID index
behind, requiring manual ``DROP INDEX`` + retry) in exchange for NOT taking
an ACCESS-EXCLUSIVE-equivalent lock that would block every collector write
for the build's duration:
  * ``snapshots.resource_id`` — measured 78,456 rows today; append-per-
    collection, the largest table in the schema by a wide margin.
  * ``resource_configs.resource_id`` — measured 0 rows today (collector not
    yet populated on this instance), but same per-resource-per-run KV write
    path as ``snapshots`` (see ``ResourceConfig`` in ``db/models/core.py``) —
    write pattern, not just current size, is what CONCURRENTLY protects.
  * ``linux_packages.host_id`` — measured 0 rows today, but
    ``agents/linux.py`` does ``session.query(LinuxPackage).filter_by(
    host_id=host_id).delete()`` then bulk-inserts fresh rows EVERY sweep,
    for EVERY host — hundreds of packages/host x fleet size. This is also
    the table TRK-330 explicitly named as the hard case.
  * The ``lb_*`` family (``lb_instances``, ``lb_pools``, ``lb_pool_members``,
    ``lb_virtual_servers`` — 6 columns across 4 tables) — TRK-330-named,
    re-collected every LB sweep including live health-check state.
  * The ``vsphere_*`` family (7 tables, one ``resource_id`` column each) —
    TRK-330-named; treated uniformly across the family (datacenters/clusters
    are small individually, but consistency with the larger members
    (``vsphere_vms``, ``vsphere_hosts``) avoids a fragile per-subtable split).
  * The ``k8s_*`` family (``k8s_nodes``, ``k8s_pods``, ``k8s_deployments``)
    — TRK-330-named; measured 0 rows (no cluster configured on this
    instance yet — see ``cloud_k8s_net.py``'s "stay idle until enabled, so
    these ship ready for when enabled" note), sized by pod/node count once
    a real cluster is attached, not by fleet host count.
  * The ``octopus_*`` family (``octopus_releases``, ``octopus_deployments``)
    — TRK-330-named; deployment history that only grows with CD activity.
  * ``cloud_resources.resource_id`` and ``net_devices.resource_id`` — NOT
    explicitly named in TRK-330's task text, added here by judgment: same
    file (``cloud_k8s_net.py``), same "idle until enabled" collector
    posture, same natural-key-upsert relational shape as ``k8s_*``, and
    sized by AWS-account-resource-count / SNMP-discovered-device-count
    respectively — neither is bounded by fleet host count the way the
    "plain" bucket below is. Flagging this explicitly since it goes beyond
    the literal family list in the task.

PLAIN (14 columns, no CONCURRENTLY) — genuinely small or fleet-size-bounded,
following the exact precedent and reasoning of ``005f5781df29``'s
``host_identities`` indexes: a plain (non-concurrent) ``CREATE INDEX`` takes
a SHARE lock, which blocks writes but NOT reads, for only the duration of
the build — sub-millisecond to low-millisecond at these row counts, and the
table's growth is bounded by a count (fleet hosts, GitLab projects, distinct
catalog entries, governance events) rather than by elapsed time:
  * ``linux_crons.host_id`` (21 rows), ``linux_ports.host_id`` (172 rows),
    ``linux_services.host_id`` (0 rows), ``linux_users.host_id`` (196 rows)
    — same per-host delete-then-reinsert write pattern as
    ``linux_packages`` (``agents/linux.py``), but bounded by a much smaller
    per-host multiplier (a handful of crons/ports/users per host vs.
    hundreds of packages), so even at full fleet size these stay small
    enough that lock duration is negligible.
  * ``ci_pipeline_runs.resource_id`` (161 rows) — looks append-only-over-time
    at first glance, but ``agents/cicd.py`` fetches only
    ``per_page=5`` pipelines per GitLab project, so the table is capped at
    roughly ``5 x project_count``, not unbounded CI history.
  * ``gitlab_projects.resource_id`` (138 rows), ``iac_files.resource_id``
    (68 rows) — one row per GitLab project / parsed IaC file; bounded by
    the GitLab instance's project count.
  * ``confluence_pages.resource_id`` (0 rows), ``container_images.resource_id``
    (0 rows), ``eol_registry.resource_id`` (3 rows), ``secret_records.
    resource_id`` (0 rows), ``r7_assets.resource_id`` (0 rows) — each
    bounded by a distinct catalog/asset count (wiki pages, registry
    images, EOL products, secrets-manager entries, Rapid7 assets), not by
    time or sweep frequency.
  * ``instinct_approvals.instinct_id`` (0 rows), ``instinct_versions.
    instinct_id`` (0 rows) — append-only audit trails, but bounded by
    human-governance-cadence (promotions/rollbacks), not collector sweeps.

3. IDEMPOTENCY GUARDS (every create_index call, not just some)
================================================================
``0001_initial_schema.py`` creates each table it "owns" (i.e. not
introduced by a dedicated later ``op.create_table`` migration) via
``Base.metadata.create_all()`` against the CURRENT models at migration-run
time. Nine of these 36 columns live on tables 0001 owns (``linux_crons``,
``linux_packages``, ``linux_ports``, ``linux_services``, ``linux_users``,
``eol_registry``, ``confluence_pages``, ``snapshots``, ``resource_configs``)
— so on a from-EMPTY replay (the ``migration-parity`` CI gate,
``tests/test_migration.py``), 0001 already creates these 9 indexes straight
from the ``index=True`` added to the models in this same change, and an
unguarded ``op.create_index`` here would collide with a duplicate-index
error. Confirmed by running autogenerate twice: once against a scratch DB
built with the ORIGINAL (pre-this-migration) models — which correctly
detected all 36 — and once against a scratch DB that had accidentally
replayed 0001 with the ALREADY-EDITED models, which only detected 27 (the
other 9 were "free" via 0001's create_all and would have silently produced
an incomplete migration if trusted). Every ``create_index``/``drop_index``
call below is therefore guarded by an inspector existence check, mirroring
0008/0026/0027/1dbf38e28aa6 — safe no-op on a fresh DB, real ALTER on an
already-migrated deploy target.

4. IS EVERY ONE OF THESE EARNING ITS WRITE COST?
==================================================
Honest answer: probably not all 36 with equal certainty, but each is
defensible as a join-path index for its table's canonical parent lookup
(``resources.id`` for almost all of them, ``linux_hosts.id`` for the Linux
per-host detail tables, ``instincts.id`` for the governance tables). The
ones most likely to see real read traffic today are ``snapshots.
resource_id`` (backs "history for this resource" — a real dashboard/chat
query path) and the ``linux_*.host_id`` columns (the per-sweep DELETE
WHERE host_id=X is itself index-bound, not just future SELECTs). The
``vsphere_*``/``k8s_*``/``octopus_*``/``lb_*``/``cloud_resources``/
``net_devices`` columns are collectors that are largely idle or
low-volume on THIS deployment right now (measured 0 rows for most of
them) — their indexes are insurance against the day those collectors are
enabled at real scale, not something paying for itself today. That is a
reasonable bet given TRK-330 explicitly named these families as the
"hard part" precisely because of their eventual scale, but it is
worth revisiting if any of these collectors are permanently retired
rather than "idle until enabled."
"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = "adacc8308153"
down_revision: Union[str, Sequence[str], None] = "74cd24313ffd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# (index_name, table, column) -- built CONCURRENTLY (large / continuously
# written; see docstring section 2).
_CONCURRENT_SPECS: list[tuple[str, str, str]] = [
    ("ix_snapshots_resource_id", "snapshots", "resource_id"),
    ("ix_resource_configs_resource_id", "resource_configs", "resource_id"),
    ("ix_linux_packages_host_id", "linux_packages", "host_id"),
    ("ix_lb_instances_resource_id", "lb_instances", "resource_id"),
    ("ix_lb_pools_resource_id", "lb_pools", "resource_id"),
    ("ix_lb_pool_members_resource_id", "lb_pool_members", "resource_id"),
    ("ix_lb_virtual_servers_resource_id", "lb_virtual_servers", "resource_id"),
    ("ix_lb_virtual_servers_pool_id", "lb_virtual_servers", "pool_id"),
    ("ix_vsphere_clusters_resource_id", "vsphere_clusters", "resource_id"),
    ("ix_vsphere_datacenters_resource_id", "vsphere_datacenters", "resource_id"),
    ("ix_vsphere_datastores_resource_id", "vsphere_datastores", "resource_id"),
    ("ix_vsphere_hosts_resource_id", "vsphere_hosts", "resource_id"),
    ("ix_vsphere_networks_resource_id", "vsphere_networks", "resource_id"),
    ("ix_vsphere_resource_pools_resource_id", "vsphere_resource_pools", "resource_id"),
    ("ix_vsphere_vms_resource_id", "vsphere_vms", "resource_id"),
    ("ix_k8s_deployments_resource_id", "k8s_deployments", "resource_id"),
    ("ix_k8s_nodes_resource_id", "k8s_nodes", "resource_id"),
    ("ix_k8s_pods_resource_id", "k8s_pods", "resource_id"),
    ("ix_octopus_deployments_resource_id", "octopus_deployments", "resource_id"),
    ("ix_octopus_releases_resource_id", "octopus_releases", "resource_id"),
    ("ix_cloud_resources_resource_id", "cloud_resources", "resource_id"),
    ("ix_net_devices_resource_id", "net_devices", "resource_id"),
]

# (index_name, table, column) -- plain CREATE INDEX (small / fleet-bounded;
# see docstring section 2).
_PLAIN_SPECS: list[tuple[str, str, str]] = [
    ("ix_ci_pipeline_runs_resource_id", "ci_pipeline_runs", "resource_id"),
    ("ix_confluence_pages_resource_id", "confluence_pages", "resource_id"),
    ("ix_container_images_resource_id", "container_images", "resource_id"),
    ("ix_eol_registry_resource_id", "eol_registry", "resource_id"),
    ("ix_gitlab_projects_resource_id", "gitlab_projects", "resource_id"),
    ("ix_iac_files_resource_id", "iac_files", "resource_id"),
    ("ix_instinct_approvals_instinct_id", "instinct_approvals", "instinct_id"),
    ("ix_instinct_versions_instinct_id", "instinct_versions", "instinct_id"),
    ("ix_r7_assets_resource_id", "r7_assets", "resource_id"),
    ("ix_secret_records_resource_id", "secret_records", "resource_id"),
    ("ix_linux_crons_host_id", "linux_crons", "host_id"),
    ("ix_linux_ports_host_id", "linux_ports", "host_id"),
    ("ix_linux_services_host_id", "linux_services", "host_id"),
    ("ix_linux_users_host_id", "linux_users", "host_id"),
]


def _existing_indexes(inspector, table: str) -> set[str]:
    try:
        return {ix["name"] for ix in inspector.get_indexes(table)}
    except Exception:
        return set()


def upgrade() -> None:
    bind = op.get_bind()
    is_pg = bind.dialect.name == "postgresql"
    inspector = inspect(bind)
    tables = set(inspector.get_table_names())

    # Plain indexes first (cheap, transactional, no dialect branching needed).
    for name, table, column in _PLAIN_SPECS:
        if table not in tables:
            continue
        if name in _existing_indexes(inspector, table):
            continue
        op.create_index(name, table, [column], unique=False)

    # CONCURRENTLY indexes: cannot run inside a transaction, so each needs its
    # own autocommit_block. SQLite (test engine) has no CONCURRENTLY concept,
    # so it falls back to a plain guarded create_index there.
    for name, table, column in _CONCURRENT_SPECS:
        if table not in tables:
            continue
        if name in _existing_indexes(inspector, table):
            continue
        if is_pg:
            with op.get_context().autocommit_block():
                op.create_index(name, table, [column], unique=False, postgresql_concurrently=True)
        else:
            op.create_index(name, table, [column], unique=False)


def downgrade() -> None:
    bind = op.get_bind()
    is_pg = bind.dialect.name == "postgresql"
    inspector = inspect(bind)
    tables = set(inspector.get_table_names())

    # Reverse order: CONCURRENTLY-built indexes first, then plain ones.
    for name, table, _column in reversed(_CONCURRENT_SPECS):
        if table not in tables:
            continue
        if name not in _existing_indexes(inspector, table):
            continue
        if is_pg:
            with op.get_context().autocommit_block():
                op.drop_index(name, table_name=table, postgresql_concurrently=True)
        else:
            op.drop_index(name, table_name=table)

    for name, table, _column in reversed(_PLAIN_SPECS):
        if table not in tables:
            continue
        if name not in _existing_indexes(inspector, table):
            continue
        op.drop_index(name, table_name=table)
