"""graph_phase2_nodes_edges

Revision ID: ec4de4fefbef
Revises: 7cf2cbe18dc1
Create Date: 2026-07-27 07:30:16.022116

Relationship Graph Phase 2 (GitLab issue #126): two NEW tables, ``graph_nodes``
and ``graph_edges``. Purely additive — no existing table, column, constraint or
index is touched, so there is no lock/backfill risk on any populated table and
every NOT NULL column is safe (the tables start empty).

The DDL below is exactly what ``alembic revision --autogenerate`` produced. The
only edit is the ``existing_tables`` inspector guard, which this repo REQUIRES
for any new table: migration ``0002_add_inventory_reconcile`` runs a blanket
``Base.metadata.create_all()`` against *today's* models, so on a from-empty
chain (CI's ``migration-parity`` gate) both tables already exist by the time
this revision runs and an unguarded ``op.create_table`` fails with
DuplicateTable. Same pattern and rationale as ``0035_mcp_api_keys``. Both paths
converge on identical DDL because ``create_all`` builds from the same metadata.

The guard also feeds ``0001_initial_schema._tables_owned_by_later_migrations()``,
which regex-scans sibling migrations for create-table calls and for
existing-tables membership checks, so that 0001 stops pre-creating any table a
later migration owns. (Do not quote those two patterns literally in prose here —
the scanner would match the docstring and report a table name that does not
exist, which ``test_0001_does_not_precreate_later_migration_tables`` rejects.)
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec4de4fefbef'
down_revision: Union[str, Sequence[str], None] = '7cf2cbe18dc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    existing_tables = set(inspect(op.get_bind()).get_table_names())

    if "graph_nodes" not in existing_tables:
        op.create_table('graph_nodes',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('node_type', sa.String(length=64), nullable=False),
        sa.Column('natural_key', sa.String(length=512), nullable=False),
        sa.Column('name', sa.String(length=256), nullable=False),
        sa.Column('source', sa.String(length=64), nullable=False),
        sa.Column('resource_id', sa.UUID(), nullable=True),
        sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
        sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name='fk_graph_nodes_resource', ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('node_type', 'natural_key', name='uq_graph_nodes_identity')
        )
        op.create_index('ix_graph_nodes_resource', 'graph_nodes', ['resource_id'], unique=False)
        op.create_index('ix_graph_nodes_type', 'graph_nodes', ['node_type'], unique=False)
    if "graph_edges" not in existing_tables:
        op.create_table('graph_edges',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('source_id', sa.UUID(), nullable=False),
        sa.Column('target_id', sa.UUID(), nullable=False),
        sa.Column('edge_type', sa.String(length=64), nullable=False),
        sa.Column('method', sa.String(length=32), nullable=False),
        sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
        sa.Column('source', sa.String(length=128), nullable=False),
        sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
        sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['source_id'], ['graph_nodes.id'], name='fk_graph_edges_source', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['target_id'], ['graph_nodes.id'], name='fk_graph_edges_target', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_graph_edges_source', 'graph_edges', ['source_id'], unique=False)
        op.create_index('ix_graph_edges_target', 'graph_edges', ['target_id'], unique=False)
        op.create_index('ix_graph_edges_type', 'graph_edges', ['edge_type'], unique=False)
        op.create_index('uq_graph_edges_active', 'graph_edges', ['source_id', 'target_id', 'edge_type'], unique=True, postgresql_where=sa.text('valid_to IS NULL'), sqlite_where=sa.text('valid_to IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_graph_edges_active', table_name='graph_edges', postgresql_where=sa.text('valid_to IS NULL'), sqlite_where=sa.text('valid_to IS NULL'))
    op.drop_index('ix_graph_edges_type', table_name='graph_edges')
    op.drop_index('ix_graph_edges_target', table_name='graph_edges')
    op.drop_index('ix_graph_edges_source', table_name='graph_edges')
    op.drop_table('graph_edges')
    op.drop_index('ix_graph_nodes_type', table_name='graph_nodes')
    op.drop_index('ix_graph_nodes_resource', table_name='graph_nodes')
    op.drop_table('graph_nodes')
    # ### end Alembic commands ###
