"""phase6 agent task runs

Revision ID: f8dfd053ec66
Revises: 87ed7c6601d0
Create Date: 2026-08-01 03:33:06.166598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8dfd053ec66'
down_revision: Union[str, Sequence[str], None] = '87ed7c6601d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_task_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_name', sa.String(length=128), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result_meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_task_runs_started_at', 'agent_task_runs', ['started_at'], unique=False)
    op.create_index('ix_agent_task_runs_task_name', 'agent_task_runs', ['task_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agent_task_runs_task_name', table_name='agent_task_runs')
    op.drop_index('ix_agent_task_runs_started_at', table_name='agent_task_runs')
    op.drop_table('agent_task_runs')
    # ### end Alembic commands ###
