#!/usr/bin/env python3
"""Regenerate `docs/GITLAB-ISSUES-SNAPSHOT.md` — a full offline copy of every open
GitLab issue (metadata + complete description body).

WHY THIS EXISTS
---------------
`docs/TRACKER.md` carries the *index*: issue number, priority, title, and — for the
2026-07-31 audit batch — the code-validated verdict. That is enough to answer "what's
open" and "what's p0" without an API call, but not "what did #182 actually say?".

The bodies are ~125KB across 61 issues, which would roughly double TRACKER.md and
undo the 2026-07-30 split that made it scannable again. So they live here instead,
and TRACKER.md links to this file.

USAGE
-----
    python scripts/snapshot_gitlab_issues.py            # writes docs/GITLAB-ISSUES-SNAPSHOT.md
    python scripts/snapshot_gitlab_issues.py --check    # exit 1 if the snapshot is stale

Requires `glab` authenticated against the project (same dependency the rest of the
repo's GitLab tooling already has). Read-only: this only ever calls GET on the issues
API and writes one local markdown file — it never mutates GitLab.

CAVEAT worth preserving: the output is a point-in-time snapshot, not a live view. It
is only as current as the last run. The header of the generated file says so.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
OUT_PATH = REPO_ROOT / "docs" / "GITLAB-ISSUES-SNAPSHOT.md"

# Ordering for the priority labels this repo uses; anything else sorts last.
PRIORITY_ORDER = {
    "priority-p0": 0,
    "priority-p1": 1,
    "priority-p2": 2,
    "priority-p3-deferred": 3,
}
PRIORITY_SHORT = {
    "priority-p0": "p0",
    "priority-p1": "p1",
    "priority-p2": "p2",
    "priority-p3-deferred": "p3",
}


def fetch_open_issues() -> list[dict]:
    """GET every open issue via glab. Raises on a non-zero exit rather than
    silently snapshotting a partial/empty set — a truncated snapshot that looks
    complete is worse than no snapshot."""
    proc = subprocess.run(
        ["glab", "api", "projects/:id/issues?state=opened&per_page=100"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        raise SystemExit(f"glab api failed (exit {proc.returncode}):\n{proc.stderr.strip()}")
    try:
        issues = json.loads(proc.stdout)
    except json.JSONDecodeError as exc:
        raise SystemExit(f"could not parse glab output as JSON: {exc}")
    if not isinstance(issues, list):
        raise SystemExit(f"expected a JSON list of issues, got {type(issues).__name__}")
    if not issues:
        raise SystemExit("glab returned zero open issues — refusing to write an empty snapshot")
    return issues


def priority_of(issue: dict) -> str | None:
    for label in issue.get("labels", []):
        if label in PRIORITY_ORDER:
            return label
    return None


def sort_key(issue: dict) -> tuple[int, int]:
    p = priority_of(issue)
    return (PRIORITY_ORDER.get(p, 9), issue["iid"])


def render(issues: list[dict]) -> str:
    issues = sorted(issues, key=sort_key)

    counts: dict[str, int] = {}
    for i in issues:
        counts[PRIORITY_SHORT.get(priority_of(i), "unlabeled")] = (
            counts.get(PRIORITY_SHORT.get(priority_of(i), "unlabeled"), 0) + 1
        )
    spread = " · ".join(
        f"{counts[k]} {k}" for k in ["p0", "p1", "p2", "p3", "unlabeled"] if k in counts
    )

    out: list[str] = []
    out.append("# GitLab open-issue snapshot — full descriptions")
    out.append("")
    out.append(
        "**Generated by `scripts/snapshot_gitlab_issues.py`. Do not hand-edit — "
        "re-run the script instead.**"
    )
    out.append("")
    out.append(
        "Offline copy of every open GitLab issue, body included, so investigating an "
        "issue does not require an API round-trip. The scannable index (number, "
        "priority, title, and the code-validated verdicts from the 2026-07-31 pass) "
        "lives in [`docs/TRACKER.md`](TRACKER.md) — this file is the long-form companion "
        "and is deliberately kept separate so TRACKER.md stays readable."
    )
    out.append("")
    out.append(
        "> **This is a point-in-time snapshot, not a live view.** It is only as current "
        "as the last run of the generator. Re-run it, or check `glab issue list`, before "
        "relying on state for anything consequential."
    )
    out.append("")
    out.append(f"**{len(issues)} open** — {spread}")
    out.append("")
    out.append("---")
    out.append("")

    # ---- contents -------------------------------------------------------
    out.append("## Contents")
    out.append("")
    out.append("| # | Pri | Title |")
    out.append("|---|---|---|")
    for i in issues:
        pri = PRIORITY_SHORT.get(priority_of(i), "—")
        title = (i["title"] or "").replace("|", "\\|").strip()
        out.append(f"| [{i['iid']}](#issue-{i['iid']}) | {pri} | {title} |")
    out.append("")
    out.append("---")
    out.append("")

    # ---- bodies ---------------------------------------------------------
    for i in issues:
        pri = PRIORITY_SHORT.get(priority_of(i), "—")
        labels = ", ".join(f"`{lab}`" for lab in i.get("labels", [])) or "_none_"
        created = (i.get("created_at") or "")[:10]
        updated = (i.get("updated_at") or "")[:10]
        title = (i["title"] or "").strip()

        out.append(f'<a id="issue-{i["iid"]}"></a>')
        out.append("")
        out.append(f"## #{i['iid']} — {title}")
        out.append("")
        out.append(f"**Priority:** {pri} · **Created:** {created} · **Updated:** {updated}  ")
        out.append(f"**Labels:** {labels}  ")
        out.append(f"**URL:** {i.get('web_url', '')}")
        out.append("")
        body = (i.get("description") or "").strip()
        out.append(body if body else "_(no description)_")
        out.append("")
        out.append("---")
        out.append("")

    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the on-disk snapshot differs from freshly-fetched state",
    )
    args = ap.parse_args()

    content = render(fetch_open_issues())

    if args.check:
        if not OUT_PATH.exists():
            print(f"STALE: {OUT_PATH.relative_to(REPO_ROOT)} does not exist", file=sys.stderr)
            return 1
        if OUT_PATH.read_text() != content:
            print(
                f"STALE: {OUT_PATH.relative_to(REPO_ROOT)} differs from live GitLab state "
                f"— re-run `python scripts/snapshot_gitlab_issues.py`",
                file=sys.stderr,
            )
            return 1
        print(f"OK: {OUT_PATH.relative_to(REPO_ROOT)} matches live state")
        return 0

    OUT_PATH.write_text(content)
    print(f"wrote {OUT_PATH.relative_to(REPO_ROOT)} ({len(content):,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
